// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bvh_cache.proto
// Protobuf C++ Version: 5.29.3

#ifndef bvh_5fcache_2eproto_2epb_2eh
#define bvh_5fcache_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_bvh_5fcache_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_bvh_5fcache_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_bvh_5fcache_2eproto;
namespace frame {
namespace proto {
class BvhCache;
struct BvhCacheDefaultTypeInternal;
extern BvhCacheDefaultTypeInternal _BvhCache_default_instance_;
class BvhCache_BvhNode;
struct BvhCache_BvhNodeDefaultTypeInternal;
extern BvhCache_BvhNodeDefaultTypeInternal _BvhCache_BvhNode_default_instance_;
}  // namespace proto
}  // namespace frame
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace frame {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class BvhCache_BvhNode final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:frame.proto.BvhCache.BvhNode) */ {
 public:
  inline BvhCache_BvhNode() : BvhCache_BvhNode(nullptr) {}
  ~BvhCache_BvhNode() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BvhCache_BvhNode* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BvhCache_BvhNode));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BvhCache_BvhNode(
      ::google::protobuf::internal::ConstantInitialized);

  inline BvhCache_BvhNode(const BvhCache_BvhNode& from) : BvhCache_BvhNode(nullptr, from) {}
  inline BvhCache_BvhNode(BvhCache_BvhNode&& from) noexcept
      : BvhCache_BvhNode(nullptr, std::move(from)) {}
  inline BvhCache_BvhNode& operator=(const BvhCache_BvhNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline BvhCache_BvhNode& operator=(BvhCache_BvhNode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BvhCache_BvhNode& default_instance() {
    return *internal_default_instance();
  }
  static inline const BvhCache_BvhNode* internal_default_instance() {
    return reinterpret_cast<const BvhCache_BvhNode*>(
        &_BvhCache_BvhNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BvhCache_BvhNode& a, BvhCache_BvhNode& b) { a.Swap(&b); }
  inline void Swap(BvhCache_BvhNode* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BvhCache_BvhNode* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BvhCache_BvhNode* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BvhCache_BvhNode>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BvhCache_BvhNode& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BvhCache_BvhNode& from) { BvhCache_BvhNode::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BvhCache_BvhNode* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "frame.proto.BvhCache.BvhNode"; }

 protected:
  explicit BvhCache_BvhNode(::google::protobuf::Arena* arena);
  BvhCache_BvhNode(::google::protobuf::Arena* arena, const BvhCache_BvhNode& from);
  BvhCache_BvhNode(::google::protobuf::Arena* arena, BvhCache_BvhNode&& from) noexcept
      : BvhCache_BvhNode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMinXFieldNumber = 1,
    kMinYFieldNumber = 2,
    kMinZFieldNumber = 3,
    kMaxXFieldNumber = 4,
    kMaxYFieldNumber = 5,
    kMaxZFieldNumber = 6,
    kLeftFieldNumber = 7,
    kRightFieldNumber = 8,
    kFirstTriangleFieldNumber = 9,
    kTriangleCountFieldNumber = 10,
  };
  // float min_x = 1;
  void clear_min_x() ;
  float min_x() const;
  void set_min_x(float value);

  private:
  float _internal_min_x() const;
  void _internal_set_min_x(float value);

  public:
  // float min_y = 2;
  void clear_min_y() ;
  float min_y() const;
  void set_min_y(float value);

  private:
  float _internal_min_y() const;
  void _internal_set_min_y(float value);

  public:
  // float min_z = 3;
  void clear_min_z() ;
  float min_z() const;
  void set_min_z(float value);

  private:
  float _internal_min_z() const;
  void _internal_set_min_z(float value);

  public:
  // float max_x = 4;
  void clear_max_x() ;
  float max_x() const;
  void set_max_x(float value);

  private:
  float _internal_max_x() const;
  void _internal_set_max_x(float value);

  public:
  // float max_y = 5;
  void clear_max_y() ;
  float max_y() const;
  void set_max_y(float value);

  private:
  float _internal_max_y() const;
  void _internal_set_max_y(float value);

  public:
  // float max_z = 6;
  void clear_max_z() ;
  float max_z() const;
  void set_max_z(float value);

  private:
  float _internal_max_z() const;
  void _internal_set_max_z(float value);

  public:
  // int32 left = 7;
  void clear_left() ;
  ::int32_t left() const;
  void set_left(::int32_t value);

  private:
  ::int32_t _internal_left() const;
  void _internal_set_left(::int32_t value);

  public:
  // int32 right = 8;
  void clear_right() ;
  ::int32_t right() const;
  void set_right(::int32_t value);

  private:
  ::int32_t _internal_right() const;
  void _internal_set_right(::int32_t value);

  public:
  // int32 first_triangle = 9;
  void clear_first_triangle() ;
  ::int32_t first_triangle() const;
  void set_first_triangle(::int32_t value);

  private:
  ::int32_t _internal_first_triangle() const;
  void _internal_set_first_triangle(::int32_t value);

  public:
  // int32 triangle_count = 10;
  void clear_triangle_count() ;
  ::int32_t triangle_count() const;
  void set_triangle_count(::int32_t value);

  private:
  ::int32_t _internal_triangle_count() const;
  void _internal_set_triangle_count(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:frame.proto.BvhCache.BvhNode)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BvhCache_BvhNode& from_msg);
    float min_x_;
    float min_y_;
    float min_z_;
    float max_x_;
    float max_y_;
    float max_z_;
    ::int32_t left_;
    ::int32_t right_;
    ::int32_t first_triangle_;
    ::int32_t triangle_count_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bvh_5fcache_2eproto;
};
// -------------------------------------------------------------------

class BvhCache final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:frame.proto.BvhCache) */ {
 public:
  inline BvhCache() : BvhCache(nullptr) {}
  ~BvhCache() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BvhCache* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BvhCache));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BvhCache(
      ::google::protobuf::internal::ConstantInitialized);

  inline BvhCache(const BvhCache& from) : BvhCache(nullptr, from) {}
  inline BvhCache(BvhCache&& from) noexcept
      : BvhCache(nullptr, std::move(from)) {}
  inline BvhCache& operator=(const BvhCache& from) {
    CopyFrom(from);
    return *this;
  }
  inline BvhCache& operator=(BvhCache&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BvhCache& default_instance() {
    return *internal_default_instance();
  }
  static inline const BvhCache* internal_default_instance() {
    return reinterpret_cast<const BvhCache*>(
        &_BvhCache_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BvhCache& a, BvhCache& b) { a.Swap(&b); }
  inline void Swap(BvhCache* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BvhCache* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BvhCache* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BvhCache>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BvhCache& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BvhCache& from) { BvhCache::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BvhCache* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "frame.proto.BvhCache"; }

 protected:
  explicit BvhCache(::google::protobuf::Arena* arena);
  BvhCache(::google::protobuf::Arena* arena, const BvhCache& from);
  BvhCache(::google::protobuf::Arena* arena, BvhCache&& from) noexcept
      : BvhCache(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using BvhNode = BvhCache_BvhNode;

  // accessors -------------------------------------------------------
  enum : int {
    kNodesFieldNumber = 6,
    kSourceRelativeFieldNumber = 2,
    kCacheRelativeFieldNumber = 5,
    kSourceSizeFieldNumber = 3,
    kSourceMtimeNsFieldNumber = 4,
    kCacheVersionFieldNumber = 1,
  };
  // repeated .frame.proto.BvhCache.BvhNode nodes = 6;
  int nodes_size() const;
  private:
  int _internal_nodes_size() const;

  public:
  void clear_nodes() ;
  ::frame::proto::BvhCache_BvhNode* mutable_nodes(int index);
  ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>* mutable_nodes();

  private:
  const ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>& _internal_nodes() const;
  ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>* _internal_mutable_nodes();
  public:
  const ::frame::proto::BvhCache_BvhNode& nodes(int index) const;
  ::frame::proto::BvhCache_BvhNode* add_nodes();
  const ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>& nodes() const;
  // string source_relative = 2;
  void clear_source_relative() ;
  const std::string& source_relative() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_source_relative(Arg_&& arg, Args_... args);
  std::string* mutable_source_relative();
  PROTOBUF_NODISCARD std::string* release_source_relative();
  void set_allocated_source_relative(std::string* value);

  private:
  const std::string& _internal_source_relative() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_relative(
      const std::string& value);
  std::string* _internal_mutable_source_relative();

  public:
  // string cache_relative = 5;
  void clear_cache_relative() ;
  const std::string& cache_relative() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cache_relative(Arg_&& arg, Args_... args);
  std::string* mutable_cache_relative();
  PROTOBUF_NODISCARD std::string* release_cache_relative();
  void set_allocated_cache_relative(std::string* value);

  private:
  const std::string& _internal_cache_relative() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cache_relative(
      const std::string& value);
  std::string* _internal_mutable_cache_relative();

  public:
  // uint64 source_size = 3;
  void clear_source_size() ;
  ::uint64_t source_size() const;
  void set_source_size(::uint64_t value);

  private:
  ::uint64_t _internal_source_size() const;
  void _internal_set_source_size(::uint64_t value);

  public:
  // uint64 source_mtime_ns = 4;
  void clear_source_mtime_ns() ;
  ::uint64_t source_mtime_ns() const;
  void set_source_mtime_ns(::uint64_t value);

  private:
  ::uint64_t _internal_source_mtime_ns() const;
  void _internal_set_source_mtime_ns(::uint64_t value);

  public:
  // uint32 cache_version = 1;
  void clear_cache_version() ;
  ::uint32_t cache_version() const;
  void set_cache_version(::uint32_t value);

  private:
  ::uint32_t _internal_cache_version() const;
  void _internal_set_cache_version(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:frame.proto.BvhCache)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 1,
      58, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BvhCache& from_msg);
    ::google::protobuf::RepeatedPtrField< ::frame::proto::BvhCache_BvhNode > nodes_;
    ::google::protobuf::internal::ArenaStringPtr source_relative_;
    ::google::protobuf::internal::ArenaStringPtr cache_relative_;
    ::uint64_t source_size_;
    ::uint64_t source_mtime_ns_;
    ::uint32_t cache_version_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_bvh_5fcache_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BvhCache_BvhNode

// float min_x = 1;
inline void BvhCache_BvhNode::clear_min_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_x_ = 0;
}
inline float BvhCache_BvhNode::min_x() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.min_x)
  return _internal_min_x();
}
inline void BvhCache_BvhNode::set_min_x(float value) {
  _internal_set_min_x(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.min_x)
}
inline float BvhCache_BvhNode::_internal_min_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_x_;
}
inline void BvhCache_BvhNode::_internal_set_min_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_x_ = value;
}

// float min_y = 2;
inline void BvhCache_BvhNode::clear_min_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_y_ = 0;
}
inline float BvhCache_BvhNode::min_y() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.min_y)
  return _internal_min_y();
}
inline void BvhCache_BvhNode::set_min_y(float value) {
  _internal_set_min_y(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.min_y)
}
inline float BvhCache_BvhNode::_internal_min_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_y_;
}
inline void BvhCache_BvhNode::_internal_set_min_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_y_ = value;
}

// float min_z = 3;
inline void BvhCache_BvhNode::clear_min_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_z_ = 0;
}
inline float BvhCache_BvhNode::min_z() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.min_z)
  return _internal_min_z();
}
inline void BvhCache_BvhNode::set_min_z(float value) {
  _internal_set_min_z(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.min_z)
}
inline float BvhCache_BvhNode::_internal_min_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.min_z_;
}
inline void BvhCache_BvhNode::_internal_set_min_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.min_z_ = value;
}

// float max_x = 4;
inline void BvhCache_BvhNode::clear_max_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_x_ = 0;
}
inline float BvhCache_BvhNode::max_x() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.max_x)
  return _internal_max_x();
}
inline void BvhCache_BvhNode::set_max_x(float value) {
  _internal_set_max_x(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.max_x)
}
inline float BvhCache_BvhNode::_internal_max_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_x_;
}
inline void BvhCache_BvhNode::_internal_set_max_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_x_ = value;
}

// float max_y = 5;
inline void BvhCache_BvhNode::clear_max_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_y_ = 0;
}
inline float BvhCache_BvhNode::max_y() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.max_y)
  return _internal_max_y();
}
inline void BvhCache_BvhNode::set_max_y(float value) {
  _internal_set_max_y(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.max_y)
}
inline float BvhCache_BvhNode::_internal_max_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_y_;
}
inline void BvhCache_BvhNode::_internal_set_max_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_y_ = value;
}

// float max_z = 6;
inline void BvhCache_BvhNode::clear_max_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_z_ = 0;
}
inline float BvhCache_BvhNode::max_z() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.max_z)
  return _internal_max_z();
}
inline void BvhCache_BvhNode::set_max_z(float value) {
  _internal_set_max_z(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.max_z)
}
inline float BvhCache_BvhNode::_internal_max_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_z_;
}
inline void BvhCache_BvhNode::_internal_set_max_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_z_ = value;
}

// int32 left = 7;
inline void BvhCache_BvhNode::clear_left() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = 0;
}
inline ::int32_t BvhCache_BvhNode::left() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.left)
  return _internal_left();
}
inline void BvhCache_BvhNode::set_left(::int32_t value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.left)
}
inline ::int32_t BvhCache_BvhNode::_internal_left() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_;
}
inline void BvhCache_BvhNode::_internal_set_left(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = value;
}

// int32 right = 8;
inline void BvhCache_BvhNode::clear_right() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = 0;
}
inline ::int32_t BvhCache_BvhNode::right() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.right)
  return _internal_right();
}
inline void BvhCache_BvhNode::set_right(::int32_t value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.right)
}
inline ::int32_t BvhCache_BvhNode::_internal_right() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_;
}
inline void BvhCache_BvhNode::_internal_set_right(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = value;
}

// int32 first_triangle = 9;
inline void BvhCache_BvhNode::clear_first_triangle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.first_triangle_ = 0;
}
inline ::int32_t BvhCache_BvhNode::first_triangle() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.first_triangle)
  return _internal_first_triangle();
}
inline void BvhCache_BvhNode::set_first_triangle(::int32_t value) {
  _internal_set_first_triangle(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.first_triangle)
}
inline ::int32_t BvhCache_BvhNode::_internal_first_triangle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.first_triangle_;
}
inline void BvhCache_BvhNode::_internal_set_first_triangle(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.first_triangle_ = value;
}

// int32 triangle_count = 10;
inline void BvhCache_BvhNode::clear_triangle_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.triangle_count_ = 0;
}
inline ::int32_t BvhCache_BvhNode::triangle_count() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.BvhNode.triangle_count)
  return _internal_triangle_count();
}
inline void BvhCache_BvhNode::set_triangle_count(::int32_t value) {
  _internal_set_triangle_count(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.BvhNode.triangle_count)
}
inline ::int32_t BvhCache_BvhNode::_internal_triangle_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.triangle_count_;
}
inline void BvhCache_BvhNode::_internal_set_triangle_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.triangle_count_ = value;
}

// -------------------------------------------------------------------

// BvhCache

// uint32 cache_version = 1;
inline void BvhCache::clear_cache_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_version_ = 0u;
}
inline ::uint32_t BvhCache::cache_version() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.cache_version)
  return _internal_cache_version();
}
inline void BvhCache::set_cache_version(::uint32_t value) {
  _internal_set_cache_version(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.cache_version)
}
inline ::uint32_t BvhCache::_internal_cache_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cache_version_;
}
inline void BvhCache::_internal_set_cache_version(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_version_ = value;
}

// string source_relative = 2;
inline void BvhCache::clear_source_relative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_relative_.ClearToEmpty();
}
inline const std::string& BvhCache::source_relative() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.source_relative)
  return _internal_source_relative();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BvhCache::set_source_relative(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_relative_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.source_relative)
}
inline std::string* BvhCache::mutable_source_relative() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_source_relative();
  // @@protoc_insertion_point(field_mutable:frame.proto.BvhCache.source_relative)
  return _s;
}
inline const std::string& BvhCache::_internal_source_relative() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_relative_.Get();
}
inline void BvhCache::_internal_set_source_relative(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_relative_.Set(value, GetArena());
}
inline std::string* BvhCache::_internal_mutable_source_relative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.source_relative_.Mutable( GetArena());
}
inline std::string* BvhCache::release_source_relative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:frame.proto.BvhCache.source_relative)
  return _impl_.source_relative_.Release();
}
inline void BvhCache::set_allocated_source_relative(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_relative_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_relative_.IsDefault()) {
    _impl_.source_relative_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:frame.proto.BvhCache.source_relative)
}

// uint64 source_size = 3;
inline void BvhCache::clear_source_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_size_ = ::uint64_t{0u};
}
inline ::uint64_t BvhCache::source_size() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.source_size)
  return _internal_source_size();
}
inline void BvhCache::set_source_size(::uint64_t value) {
  _internal_set_source_size(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.source_size)
}
inline ::uint64_t BvhCache::_internal_source_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_size_;
}
inline void BvhCache::_internal_set_source_size(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_size_ = value;
}

// uint64 source_mtime_ns = 4;
inline void BvhCache::clear_source_mtime_ns() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_mtime_ns_ = ::uint64_t{0u};
}
inline ::uint64_t BvhCache::source_mtime_ns() const {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.source_mtime_ns)
  return _internal_source_mtime_ns();
}
inline void BvhCache::set_source_mtime_ns(::uint64_t value) {
  _internal_set_source_mtime_ns(value);
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.source_mtime_ns)
}
inline ::uint64_t BvhCache::_internal_source_mtime_ns() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_mtime_ns_;
}
inline void BvhCache::_internal_set_source_mtime_ns(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_mtime_ns_ = value;
}

// string cache_relative = 5;
inline void BvhCache::clear_cache_relative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_relative_.ClearToEmpty();
}
inline const std::string& BvhCache::cache_relative() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.cache_relative)
  return _internal_cache_relative();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BvhCache::set_cache_relative(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_relative_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:frame.proto.BvhCache.cache_relative)
}
inline std::string* BvhCache::mutable_cache_relative() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_cache_relative();
  // @@protoc_insertion_point(field_mutable:frame.proto.BvhCache.cache_relative)
  return _s;
}
inline const std::string& BvhCache::_internal_cache_relative() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cache_relative_.Get();
}
inline void BvhCache::_internal_set_cache_relative(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_relative_.Set(value, GetArena());
}
inline std::string* BvhCache::_internal_mutable_cache_relative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cache_relative_.Mutable( GetArena());
}
inline std::string* BvhCache::release_cache_relative() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:frame.proto.BvhCache.cache_relative)
  return _impl_.cache_relative_.Release();
}
inline void BvhCache::set_allocated_cache_relative(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cache_relative_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cache_relative_.IsDefault()) {
    _impl_.cache_relative_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:frame.proto.BvhCache.cache_relative)
}

// repeated .frame.proto.BvhCache.BvhNode nodes = 6;
inline int BvhCache::_internal_nodes_size() const {
  return _internal_nodes().size();
}
inline int BvhCache::nodes_size() const {
  return _internal_nodes_size();
}
inline void BvhCache::clear_nodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nodes_.Clear();
}
inline ::frame::proto::BvhCache_BvhNode* BvhCache::mutable_nodes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:frame.proto.BvhCache.nodes)
  return _internal_mutable_nodes()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>* BvhCache::mutable_nodes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:frame.proto.BvhCache.nodes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_nodes();
}
inline const ::frame::proto::BvhCache_BvhNode& BvhCache::nodes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:frame.proto.BvhCache.nodes)
  return _internal_nodes().Get(index);
}
inline ::frame::proto::BvhCache_BvhNode* BvhCache::add_nodes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::frame::proto::BvhCache_BvhNode* _add = _internal_mutable_nodes()->Add();
  // @@protoc_insertion_point(field_add:frame.proto.BvhCache.nodes)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>& BvhCache::nodes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:frame.proto.BvhCache.nodes)
  return _internal_nodes();
}
inline const ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>&
BvhCache::_internal_nodes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nodes_;
}
inline ::google::protobuf::RepeatedPtrField<::frame::proto::BvhCache_BvhNode>*
BvhCache::_internal_mutable_nodes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.nodes_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace frame


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // bvh_5fcache_2eproto_2epb_2eh
