#pragma once

#include "../Frame/BindInterface.h"
#include "../Frame/BufferInterface.h"
#include "../Frame/CameraInterface.h"
#include "../Frame/DeviceInterface.h"
#include "../Frame/DrawInterface.h"
#include "../Frame/InputInterface.h"
#include "../Frame/LevelInterface.h"
#include "../Frame/LightInterface.h"
#include "../Frame/MaterialInterface.h"
#include "../Frame/ProgramInterface.h"
#include "../Frame/NodeInterface.h"
#include "../Frame/SceneTreeInterface.h"
#include "../Frame/TextureInterface.h"
#include "../Frame/UniformInterface.h"
#include "../Frame/WindowInterface.h"